version: "3.9"

services:
  laravel13:
    image: webdevops/php-apache-dev:${DC_PHP:-8.4}
    user: "${DC_UID:-1000}:${DC_GID:-1000}"
    volumes:
      - ./:/docker
      - ./vendor:/vendor
    working_dir: /docker
    environment:
      - PATH=$PATH:/home/application/.composer/vendor/bin:/home/application/.config/composer/vendor/bin
    networks:
      - frontend

networks:
  frontend: null
